### ISSUE TITLE
How to use a websocket client instead of a server with this

### ISSUE THREAD

**Issue by slidenerd** [Roger13/multiprocess-websocket-server#1]
First of all thank you for the simple example. I see worker.js file uses a websocket server. I would like to use a websocket client to connect to different servers and live stream data from each one. How would I got about that, if it isnt too much to ask, can you kindly add another worker file with a client trying to live stream from different servers? Thanks

**Comment by Roger13** [comment]
@slidenerd I'm not sure I understood the requirements. Would you want each worker process to connect to a websocket server and listen to it? If so, you can try replacing the server creation with the following snippet: 

``const webSocket = new WebSocket('ws://www.host.com/path')``

Beware that in this scenario, the master process role should also be modified with your busyness logic to coordinate the workers connections to the streaming servers, therefore you should remove the net TCP server in it as well.

That being said, I feel your request is out of the scope of this repository, but let me know if you need help modifying it!

**Comment by slidenerd** [comment]
Thanks for replying, what I was trying to convey is that I understand what your application does from a server's perspective. If there are 1 million clients and 8 cores on the CPU, the cluster tries to divide requests amongst workers if I am not mistaken

What I was asking is let's say I had 20 WSS API urls and I wanted to connect to each one but instead of burdening a single process I wanted to use all the CPUs to somehow divide the urls between each worker so that each worker at the end has 1 or more socket client connections to the urls it receives, how do I go about modifying the code to do the same

In python, I would simple use the multiprocessing module with asyncio to have different processes spawned for each url but given node is single threaded, I guess cluster is the only way out, thanks for taking your time to read this

**Comment by Roger13** [comment]
You are correct. Cluster is the way to go assuming you are not running your service under kubernates or mesos. As soon as I have time I'll create a branch with the modified scenario.

**Comment by Roger13** [comment]
Added the [multiprocess-websocket-client](https://github.com/Roger13/multiprocess-websocket-server/tree/multiprocess-websocket-client) branch, hope it helps!

**Comment by slidenerd** [comment]
OMG thank you so much!!! that is super distributed! 
In case you are looking to get some smooth points out of this in stackoverflow :) 
here are some questions that deal with this issue
[ONE](https://stackoverflow.com/questions/32500446/how-to-create-multiple-websocket-connections-from-client-using-socket-io?rq=1)
[TWO](https://stackoverflow.com/questions/24934986/swap-websocket-connections-between-multiple-clients)
[THREE](https://stackoverflow.com/questions/12498429/multiple-websockets)

I'll be more than happy to upvote on any of these questions in addition to the dude who asked them 💯
